#!/usr/bin/env python3
"""Compile unchanged configured libiberty inputs; optionally prove legacy byte identity."""
from pathlib import Path
import argparse
import hashlib
import json
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]


def digest(data):
    return hashlib.sha256(data).hexdigest()


def run(args, **kwargs):
    result = subprocess.run([str(x) for x in args], capture_output=True, timeout=120, **kwargs)
    assert result.returncode == 0, (args, result.returncode, result.stdout, result.stderr)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-root', type=Path, default=ROOT/'build-out/direct-gcc-inputs/gcc-source')
    parser.add_argument('--config-dir', type=Path, required=True)
    parser.add_argument('--baseline-root', type=Path)
    parser.add_argument('--report', type=Path)
    args = parser.parse_args()
    report = {'production_host_tools': False, 'original_units': [], 'byte_identity': []}
    source = args.source_root.resolve()
    config = args.config_dir.resolve()
    driver = ROOT/'tools/gcc-direct-cc.py'
    report['configuration_sha256'] = digest((config/'config.h').read_bytes())
    with tempfile.TemporaryDirectory(prefix='declarator-proof-') as td:
        work = Path(td)
        for name in ('spaces', 'dyn-string', 'fnmatch', 'getcwd', 'xatexit'):
            src = source/'libiberty'/(name+'.c')
            original = src.read_bytes()
            obj = work/(name+'.o')
            identity = run([driver, '--print-source-hash']).stdout.decode().strip()
            command = [driver, '-c', '-DHAVE_CONFIG_H', '-I'+str(config),
                       '-I'+str(source/'include'), src, '-o', obj]
            run(command)
            assert src.read_bytes() == original, 'Original source changed'
            report['original_units'].append({'source': str(src), 'source_sha256': digest(original),
                                            'object_sha256': digest(obj.read_bytes()),
                                            'compiler_identity': identity})
            print('PASS: unchanged configured libiberty/'+name+'.c')
        if args.baseline_root:
            names = ['010-lib.fth', *[p.name for p in sorted(ROOT.glob('[0-9][0-9][0-9]-cc-*.fth'))
                                      if p.name != '120-cc-main.fth']]
            before = {n: (args.baseline_root/n).read_bytes() for n in names}
            after = dict(before)
            for n in ('112-cc-stmt.fth', '115-cc-native.fth'):
                after[n] = (ROOT/n).read_bytes()
            report['baseline_compiler_sha256'] = {n: digest(b) for n, b in before.items()}
            report['updated_compiler_sha256'] = {n: digest(b) for n, b in after.items()}
            fixtures = [('default', 'tests/cc/C-struct-global.c', 7),
                        ('default', 'tests/cc/P3-casts.c', 74),
                        ('native', 'tests/tcc/native-layout.c', 0),
                        ('native', 'tests/tcc/native-for-lookahead.c', 0),
                        ('native', 'tests/tcc/native-stack-call.c', 0),
                        ('native', 'tests/cc/T2-native-expressions.c', 0),
                        ('native', 'tests/cc/T4-native-expression-edges.c', 0)]
            for index, (mode, name, expected) in enumerate(fixtures):
                src = (ROOT/name).read_bytes()
                artifacts = []
                for label, bundle in [('before', before), ('after', after)]:
                    output = work/(str(index)+'-'+label)
                    setup = ('true cc-target-lp64 ! true cc-prep-direct !\n[lit] 8388608 cc-arena-map\n'
                             if mode == 'native' else '')
                    setup += f'create proof-output s, {output} [lit] 0 c,\n'
                    setup += ': proof-main cc-load-stdin cc-preprocess cc-out-init cc-globals-init cc-emit-elf-header '
                    setup += ('cc-native-program' if mode == 'native' else 'cc-parse-program')
                    setup += ' cc-finalize-globals cc-finalize-elf proof-output cc-write-output bye ;\nproof-main\n'
                    result = run([args.baseline_root/'seed-forth'], input=b'\n'.join(bundle.values())+b'\n'+setup.encode()+src)
                    assert not result.stdout and not result.stderr
                    output.chmod(0o700)
                    execution = subprocess.run([output], capture_output=True, timeout=10)
                    assert execution.returncode == expected, (name, label, execution.returncode)
                    artifacts.append(output.read_bytes())
                assert artifacts[0] == artifacts[1], 'Generated bytes changed: '+name
                report['byte_identity'].append({'mode': mode, 'fixture': name, 'source_sha256': digest(src),
                                                'artifact_sha256': digest(artifacts[0]), 'exit': expected})
                print('PASS:', mode, name, 'byte-identical')
    destination = args.report or ROOT/'build-out/declarator-edges-proof.json'
    destination.write_text(json.dumps(report, indent=2, sort_keys=True)+'\n')
    print(destination)


if __name__ == '__main__':
    main()
