#!/usr/bin/env python3
"""Compare existing Python and kaem builds; never builds target tools.

Usage: python3 tests/gcc/plumbing-lexers-check.py build-out/lexers-python
Requires the GCC 4.0.4 and binutils 2.30 source caches used by gcc-direct.
Retains inputs and output hashes in build-out/plumbing/lexer-equivalence/.
"""
from pathlib import Path
import argparse
import hashlib
import json
import os
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[2]
FLEX = json.loads((ROOT / 'gcc-direct/lexer-inputs/sources.json').read_text())['archives'][2]['directory']


def digest(data):
    return hashlib.sha256(data).hexdigest()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('reference', type=Path)
    ap.add_argument('--work', type=Path, help='new comparison directory')
    args = ap.parse_args()
    reference = args.reference.resolve()
    native = ROOT / 'build-out/plumbing'
    out = args.work.resolve() if args.work else native / 'lexer-equivalence'
    out.mkdir()  # keep previous evidence rather than overwriting it
    report = {'reference': str(reference), 'prepared': {}, 'cases': {}}
    files = [('heirloom-devtools-070527/lex', n) for n in ['parser.c', 'libl.a']]
    files += [(FLEX, n) for n in ['scan.l', 'flexdef.h', 'scan.lex.l', 'scan-ascii.l',
                                'skel.c', 'parse.c', 'parse.h', 'heirloom-scan.c', 'scan-tmp.c', 'scan.c']]
    for directory, name in files:
        a = (reference / 'sources' / directory / name).read_bytes()
        b = (native / 'src' / directory / name).read_bytes()
        assert a == b, (directory, name, digest(a), digest(b))
        report['prepared'][directory + '/' + name] = digest(a)
    assert (reference / 'oyacc/production/config.h').read_bytes() == (ROOT / 'plumbing/oyacc-6.6/config.h').read_bytes()
    assert (native / 'src' / FLEX / 'config.h').read_bytes() == (reference / 'sources' / FLEX / 'config.h').read_bytes() + b'#define VERSION "2.5.11"\n'
    tools = {
        'oyacc': reference / 'oyacc/production/oyacc',
        'lex': reference / 'sources/heirloom-devtools-070527/lex/lex',
        'flex': reference / 'sources' / FLEX / 'flex',
    }
    env = dict(os.environ, LC_ALL='C')

    def compare(label, tool, source, flags=(), outputs=('lex.yy.c',)):
        directory = out / label
        directory.mkdir()
        shutil.copyfile(source, directory / source.name)
        commands = []
        results = []
        for executable in [tools[tool], native / 'bin' / tool]:
            command = [str(executable), *flags, source.name]
            result = subprocess.run(command, cwd=directory, env=env, capture_output=True, timeout=120)
            assert result.returncode == 0, (label, command, result.stderr)
            results.append((result.stdout, result.stderr, {n: (directory / n).read_bytes() for n in outputs}))
            commands.append(command)
            for name in outputs:
                (directory / name).unlink()
        assert results[0] == results[1], label
        for name, data in results[1][2].items():
            (directory / name).write_bytes(data)
        report['cases'][label] = {'commands': commands, 'input_sha256': digest(source.read_bytes()),
                                 'outputs': {n: digest(b) for n, b in results[1][2].items()}}
        print('PASS:', label)

    gcc = ROOT / 'build-out/direct-gcc-inputs/gcc-source/gcc'
    original = gcc / 'c-parse.in'
    grammar = out / 'c-parse.y'
    # Original GCC Makefile.in c-parse.y rule: remove ObjC blocks and C markers.
    prepared = subprocess.run(['sed', '-e', '/^@@ifobjc.*/,/^@@end_ifobjc.*/d',
                               '-e', '/^@@ifc.*/d', '-e', '/^@@end_ifc.*/d', str(original)],
                              check=True, capture_output=True, env=env).stdout
    grammar.write_bytes(b'/*WARNING: This file is automatically generated!*/\n' + prepared)
    report['gcc_c_parse_in_sha256'] = digest(original.read_bytes())
    compare('gcc-c-parse', 'oyacc', grammar, ('-d', '-v', '-o', 'c-parse.c'),
            ('c-parse.c', 'c-parse.h', 'y.output'))
    compare('gcc-gengtype', 'flex', gcc / 'gengtype-lex.l')
    binutils = ROOT / 'build-out/stage-b-inputs/binutils-source'
    for name in ['binutils/arlex.l', 'binutils/deflex.l', 'binutils/syslex.l',
                 'gas/itbl-lex.l', 'gas/config/bfin-lex.l', 'ld/ldlex.l']:
        compare('binutils-' + Path(name).stem, 'flex', binutils / name)
    compare('flex-scanner', 'flex', reference / 'sources' / FLEX / 'scan.l')
    compare('heirloom-bootstrap-scanner', 'lex', reference / 'sources' / FLEX / 'scan-ascii.l')
    (out / 'report.json').write_text(json.dumps(report, indent=2) + '\n')
    print('PASS: preparation and', len(report['cases']), 'consumer cases byte-identical')
    print(out / 'report.json')


if __name__ == '__main__':
    main()
