#!/usr/bin/env bash
# The host compiler is an interoperability oracle only; all target .o bytes
# are generated by seed-forth. No oracle artifact is a bootstrap input.
set -euo pipefail
cd "$(dirname "$0")/../.."
work=$(mktemp -d /tmp/sf-sysv-interop.XXXXXX)
trap 'rm -rf "$work"' EXIT
tests/gcc/sysv-object-compile.sh tests/gcc/sysv-interop.c "$work/forth.o"
${CC:-cc} -std=c99 -O2 -Wall -Wextra -fno-pie -no-pie \
  tests/gcc/sysv-interop-host.c "$work/forth.o" -o "$work/check"
"$work/check"
