/* config.h for the seed-forth bash build (from live-bootstrap common.mk) */
#define HAVE_DIRENT_H 1
#define STRUCT_DIRENT_HAS_D_INO 1
#define HAVE_STDINT_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define RETSIGTYPE void
#define HUGE_VAL 10000000000.0
#define TERMIOS_TTY_DRIVER 1
#define PREFER_STDARG 1
#define HAVE_DECL_STRTOL 1
#define HAVE_DECL_STRTOLL 1
#define HAVE_DECL_STRTOUL 1
#define HAVE_DECL_STRTOULL 1
#define HAVE_TZNAME 1
#define PIPESIZE 4096
#define DEFAULT_PATH_VALUE "/usr/bin"
#define STANDARD_UTILS_PATH "/usr/bin"
#define PPROMPT "$ "
#define SPROMPT "$ "
#define CONF_MACHTYPE "bootstrap"
#define GETGROUPS_T int
#define COND_COMMAND 1
#define CONF_HOSTTYPE "i386"
#define CONF_OSTYPE "linux"
#define DEFAULT_MAIL_DIRECTORY "/fake-mail"
#define VOID_SIGHANDLER 1
#define DISTVERSION "2.05b"
#define BUILDVERSION 0
#define SCCSVERSION "2.05b"
#define LC_ALL "C"
#define HAVE_STRERROR 1
#define HAVE_MEMSET 1
#define HAVE_DUP2 1
#define HAVE_STRTOUL 1
#define HAVE_STRTOULL 1
#define HAVE_STRCHR 1
#define HAVE_BCOPY 1
#define HAVE_BZERO 1
#define HAVE_POSIX_SIGNALS 1
#define HAVE_GETCWD 1
#define HAVE_RENAME 1
#define HAVE_SYS_SIGLIST 1
#define enable_hostname_completion(on_or_off) 0
/* Honest answers for runtime/gcc-seed (headers and functions it provides). */
#define HAVE_UNISTD_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_SYS_FILE_H 1
#define HAVE_FCNTL_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TIMES_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_LOCALE_H 1
#define HAVE_STDARG_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_WAITPID 1
#define HAVE_GETRLIMIT 1
#define HAVE_GETPWNAM 1
#define HAVE_GETPWUID 1
#define HAVE_GETPWENT 1
#define HAVE_GETHOSTNAME 1
#define HAVE_GETGROUPS 1
#define HAVE_TCGETATTR 1
#define HAVE_TIMES 1
#define HAVE_STRSIGNAL 1
#define HAVE_SETLOCALE 1
#define HAVE_STRCASECMP 1
#define HAVE_STRTOD 1
#define HAVE_STRTOL 1
#define HAVE_DECL_STRSIGNAL 1
#define HAVE_GETPAGESIZE 1
#define HAVE_GETDTABLESIZE 1
#define HAVE_SYSCONF 1
#define HAVE_UNAME 1
#define HAVE_TZSET 1
#define HAVE_LSTAT 1
#define HAVE_READLINK 1
#define USE_VARARGS 1
#define HAVE_VPRINTF 1
#define PROTOTYPES 1
#define HAVE_SNPRINTF 1
#define HAVE_VSNPRINTF 1
#define HAVE_STRFTIME 1
#define HAVE_STRPBRK 1
#define HAVE_GETCWD 1
#define HAVE_STRTOLL 1
#define HAVE_STRTOULL 1
#define HAVE_STRTOIMAX 1
#define HAVE_STRTOUMAX 1
#define HAVE_KILLPG 1
#define STACK_DIRECTION -1
