struct Pair { short a; int b; char tag[4]; };
struct Row { int op; unsigned long bits; int arg[3]; };
static int scalar = (3 << 4) + 7;
static short small = -123;
static unsigned char bytes[] = {1, 255, 3,};
static int rows_inferred[][2] = {{10, 11}, {12, 13}};
static const char inferred_months[][4] = {"Jan", "Feb"};
static const char months[3][4] = {"Jan", "Feb", "Mar"};
static char inferred[] = "a\nb" "cd";
static char exactly[3] = "abc";
static char braced[4] = {"abc"};
static char braced_inferred[] = {"hello"};
union U { long a; char bytes[8]; };
static union U uni = {0x12345678};
struct Header { char name[16]; char date[12]; char end[2]; };
static struct Header header = {"/               ", "            ", "`\n"};
static char *strings[] = {"fi" "rst", "sec" "ond", 0};
static struct Pair pairs[] = {{2, 123456, "one"}, {3, -8, "two"}};
static const struct Row rows[] = {{1, (unsigned long)1 << 40, {3, 4, 5}}, {2, 23, {6, 7}}};
static int *ptr = &scalar;
static struct Pair *second = pairs + 1;
static unsigned long field_offset = (unsigned long)&((struct Pair *)0)->b;
static int fn(int x);
static int (*fp)(int) = fn;
static int fn(int x) { static int count = 4; count += x; return count; }
int main(void) {
  struct Pair zero = {0};
  struct Pair copy = pairs[0];
  int local[] = {7, 9, 11};
  int flat[2][2] = {1, 2, 3, 4};
  char text[8] = "hi";
  int dynamic[2] = {fn(1), fn(2)};
  static unsigned long local_array_size = sizeof(dynamic);
  static unsigned long unevaluated = sizeof((dynamic[0] = 99, fn(0)));
  if (scalar != 55 || small != -123 || bytes[1] != 255 || sizeof(bytes) != 3) return 1;
  if (months[1][1] != 'e' || months[2][3] != 0) return 2;
  if (inferred[1] != '\n' || inferred[4] != 'd' || sizeof(inferred) != 6) return 3;
  if (braced[2] != 'c' || braced[3] != 0 || exactly[2] != 'c' || strings[1][2] != 'c' || strings[2] != 0) return 4;
  if (pairs[0].b != 123456 || pairs[1].tag[2] != 'o' || second->a != 3) return 5;
  if (rows[0].bits != ((unsigned long)1 << 40) || rows[1].arg[2] != 0) return 6;
  if (zero.b != 0 || zero.tag[3] != 0 || copy.b != 123456 || text[7] != 0) return 7;
  if (local[2] != 11 || sizeof(local) != 12 || flat[1][0] != 3) return 8;
  if (ptr != &scalar || *ptr != 55 || field_offset != 4) return 9;
  if (dynamic[0] != 5 || dynamic[1] != 7 || fp(2) != 9 || fn(3) != 12) return 10;
  if (sizeof(braced_inferred) != 6 || braced_inferred[4] != 'o' || uni.a != 0x12345678) return 11;
  if (header.name[15] != ' ' || header.date[11] != ' ' || header.end[1] != '\n') return 12;
  if (sizeof(rows_inferred) != 16 || rows_inferred[1][1] != 13 || sizeof(inferred_months) != 8) return 13;
  if (local_array_size != 8 || unevaluated != 4 || dynamic[0] != 5) return 14;
  return 0;
}
