#!/usr/bin/env python3
"""Stage D: GCC 4.0.4 rebuilds itself from the Forth-built compiler to a fixed point.

Usage:
    python3 gcc-direct/stage-d.py WORK --stage-c STAGE_C_WORK \\
        --oyacc OYACC --flex FLEX [-j JOBS]

STAGE_C_WORK is a finished gcc-direct/stage-c.py run: its installed GCC
(gcc/install/bin/gcc, whose cc1 and driver were built by the Forth compiler),
its musl sysroot and its Forth-built binutils (toolchain/).  This recipe then
builds GCC 4.0.4 (C only) three times, the way gcc64/build-gcc4.sh does
(libiberty, libcpp and gcc configured one by one, no fixincludes), each time
with the previous generation as the compiler:

  stage 2  built by the stage-C GCC        installed at WORK/prefix
  stage 3  built by stage 2                installed with DESTDIR=WORK/stage3
  stage 4  built by stage 3                installed with DESTDIR=WORK/stage4

Every build uses the same source path, build path and prefix, so the paths
compiled into the binaries agree.  The pass criterion is a fixed point
reached at once: stages 2, 3 and 4 must install the same files with the same
bytes, so the GCC compiled by the Forth-built cc1 is already the GCC that GCC
compiles.  Archives are compared member by member (names, order, and member
bytes), because binutils 2.30 `ar` stores member timestamps by default.

Stage 2 can match only because the runtime's qsort is musl's.  The stage-C
cc1 runs on the Forth-built runtime, not musl, and GCC 4.0.4 sorts with
comparators that tie: simplify_plus_minus (simplify-rtx.c) orders two
registers of equal commutative_operand_precedence, for example.  ISO C leaves
the order of equal elements unspecified, so it is the qsort, not the source,
that decides between `(%rbp,%rax)` and `(%rax,%rbp)`.  With the earlier
heapsort, stage 2 differed from stage 3 in seven executables by exactly such
choices; see runtime/gcc-seed/SORT.md.

Source adaptation (applied to a fresh extraction, verified before and after):
GCC 4.0.4's gcc/system.h treats Berkeley-yacc output (YYBYACC, which the
Forth-built oyacc defines) as parser-generator code where it maps malloc to
xmalloc, but its malloc/realloc poison exemption names only FLEX_SCANNER and
YYBISON, so a byacc-family parser cannot be compiled by a real GCC.  The
exemption is made to match.  The repository's collect2 patch
(patches/gcc64/gcc-4.0.4/) is applied as in gcc64/build-gcc4.sh.  Parsers and
scanners are generated by the Forth-built oyacc and flex; no host compiler,
assembler, linker, library or parser generator is used.
"""
from pathlib import Path
import argparse
import hashlib
import json
import os
import resource
import subprocess
import sys
import tarfile
import time

ROOT = Path(__file__).resolve().parents[1]
TRIPLE = "x86_64-pc-linux-gnu"
ARCHIVE = ROOT / "build-out/direct-gcc-inputs/gcc-4.0.4-git-944765863e.tar"
SKIP = ("libjava", "gcc/testsuite", "libgfortran", "libstdc++-v3", "libada", "gcc/ada", "boehm-gc",
        "libffi", "gcc/java", "gcc/fortran", "gcc/cp", "gcc/objc", "gcc/objcp", "gcc/treelang", "libobjc")
POISON_OLD = "#if !defined(FLEX_SCANNER) && !defined(YYBISON)"
POISON_NEW = "#if !defined(FLEX_SCANNER) && !defined(YYBISON) && !defined(YYBYACC)"


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def run(command, cwd, environment, log):
    with log.open("ab") as stream:
        stream.write(("\n$ " + " ".join(map(str, command)) + "\n").encode())
        stream.flush()
        result = subprocess.run(command, cwd=cwd, env=environment, stdout=stream, stderr=subprocess.STDOUT)
    if result.returncode:
        raise SystemExit(f"failed ({result.returncode}): {' '.join(map(str, command))}; see {log}")


def extract(source):
    """A fresh C-only GCC tree with the documented adaptations."""
    if source.exists():
        subprocess.run(["rm", "-rf", str(source)], check=True)
    staging = source.with_name(source.name + ".tmp")
    staging.mkdir(parents=True)
    with tarfile.open(ARCHIVE) as tape:
        members = [m for m in tape if not any(m.name.startswith(f"gcc-4.0.4/{s}/") or m.name == f"gcc-4.0.4/{s}"
                                              for s in SKIP)]
        tape.extractall(staging, members=members, filter="tar")
    (staging / "gcc-4.0.4").rename(source)
    staging.rmdir()
    system_h = source / "gcc/system.h"
    lines = system_h.read_text().split("\n")
    if lines.count(POISON_OLD) != 1:
        raise SystemExit("unexpected gcc/system.h: poison exemption line not found exactly once")
    system_h.write_text("\n".join(POISON_NEW if line == POISON_OLD else line for line in lines))
    for patch in sorted((ROOT / "patches/gcc64/gcc-4.0.4").glob("*.diff")):
        subprocess.run(["patch", "-s", "-p1", "-F0", "-i", str(patch)], cwd=source, check=True)


def build(name, compiler, work, stage_c, args, destdir=None):
    """Configure, build and install one GCC generation with COMPILER."""
    source, prefix, log = work / "src/gcc-4.0.4-work", work / "prefix", work / f"{name}.log"
    sysroot, tools = stage_c / "sysroot", stage_c / "toolchain"
    started = time.time()
    log.write_bytes(b"")
    extract(source)
    environment = dict(os.environ, LC_ALL="C", CC=str(compiler), CPP=f"{compiler} -E", CFLAGS="-O2",
                       LDFLAGS="-static", AR=str(tools / "ar"), RANLIB=str(tools / "ranlib"),
                       BISON=str(args.oyacc), YACC=str(args.oyacc), FLEX=str(args.flex), LEX=str(args.flex))
    build_dir = source / "build"
    for component in ("libiberty", "libcpp", "gcc"):
        (build_dir / component).mkdir(parents=True)
        run([f"../../{component}/configure", f"--prefix={prefix}", f"--build={TRIPLE}", f"--host={TRIPLE}",
             f"--target={TRIPLE}", "--disable-shared", "--disable-nls", "--disable-multilib",
             "--enable-languages=c", f"--with-sysroot={sysroot}", f"--with-as={tools / 'as'}",
             f"--with-ld={tools / 'ld'}", "--program-transform-name="], build_dir / component, environment, log)
    (build_dir / f"build-{TRIPLE}").symlink_to(".")
    (build_dir / "gcc/include").mkdir()
    (build_dir / "gcc/include/syslimits.h").symlink_to("../../../gcc/gsyslimits.h")
    makefile = build_dir / "gcc/Makefile"
    makefile.write_text(makefile.read_text().replace("\nSTMP_FIXINC = stmp-fixinc\n", "\nSTMP_FIXINC =\n"))
    overrides = ["CFLAGS=-O2", "LDFLAGS=-static", f"LIBGCC2_INCLUDES=-I{sysroot}/usr/include",
                 f"BISON={args.oyacc}", f"YACC={args.oyacc}", f"FLEX={args.flex}", f"LEX={args.flex}",
                 "MAKEINFO=true", f"AR={tools / 'ar'}", f"RANLIB={tools / 'ranlib'}"]
    for component in ("libiberty", "libcpp", "gcc"):
        run(["make", "-j", str(args.jobs), *overrides], build_dir / component, environment, log)
    installed = Path(str(destdir) + str(prefix)) if destdir else prefix
    (installed / f"lib/gcc/{TRIPLE}/4.0.4/install-tools/include").mkdir(parents=True, exist_ok=True)
    run(["make", "install", "MAKEINFO=true", *([f"DESTDIR={destdir}"] if destdir else [])],
        build_dir / "gcc", environment, log)
    limits = installed / f"lib/gcc/{TRIPLE}/4.0.4/include/syslimits.h"
    limits.unlink(missing_ok=True)
    limits.write_bytes((source / "gcc/gsyslimits.h").read_bytes())
    return {"stage": name, "compiler": str(compiler), "installed": str(installed),
            "seconds": round(time.time() - started, 1), "log": str(log)}


def archive_members(path, tools):
    """Archive member names in order and each member's bytes, via our ar."""
    names = subprocess.run([tools / "ar", "t", path], capture_output=True, text=True, check=True).stdout.split()
    return [(name, hashlib.sha256(subprocess.run([tools / "ar", "p", path, name], capture_output=True,
                                                 check=True).stdout).hexdigest()) for name in names]


def compare(a, b, tools):
    files_a = sorted(str(p.relative_to(a)) for p in a.rglob("*") if p.is_file())
    files_b = sorted(str(p.relative_to(b)) for p in b.rglob("*") if p.is_file())
    differing = []
    for name in sorted(set(files_a) & set(files_b)):
        if sha(a / name) == sha(b / name):
            continue
        if name.endswith(".a") and archive_members(a / name, tools) == archive_members(b / name, tools):
            continue
        differing.append(name)
    return {"files": len(files_a), "only_in_first": sorted(set(files_a) - set(files_b)),
            "only_in_second": sorted(set(files_b) - set(files_a)), "differing": differing}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("work", type=Path)
    parser.add_argument("--stage-c", type=Path, required=True)
    parser.add_argument("--oyacc", type=Path, required=True)
    parser.add_argument("--flex", type=Path, required=True)
    parser.add_argument("-j", "--jobs", type=int, default=8)
    args = parser.parse_args()
    work, stage_c = args.work.resolve(), args.stage_c.resolve()
    args.oyacc, args.flex = args.oyacc.resolve(), args.flex.resolve()
    work.mkdir(parents=True, exist_ok=False)
    # The stage-C cc1 was compiled by the Forth compiler, whose frames are larger
    # than GCC's; some GCC sources recurse deeply enough to need more stack.
    resource.setrlimit(resource.RLIMIT_STACK, (64 << 20, resource.getrlimit(resource.RLIMIT_STACK)[1]))
    prefix = work / "prefix"
    steps = [build("stage2", stage_c / "gcc/install/bin/gcc", work, stage_c, args)]
    print(f"stage 2 built in {steps[-1]['seconds']} s", flush=True)
    steps.append(build("stage3", prefix / "bin/gcc", work, stage_c, args, work / "stage3"))
    print(f"stage 3 built in {steps[-1]['seconds']} s", flush=True)
    stage3 = Path(str(work / "stage3") + str(prefix))
    steps.append(build("stage4", stage3 / "bin/gcc", work, stage_c, args, work / "stage4"))
    print(f"stage 4 built in {steps[-1]['seconds']} s", flush=True)
    stage4 = Path(str(work / "stage4") + str(prefix))
    tools = stage_c / "toolchain"
    fixed = compare(stage3, stage4, tools)
    second = compare(prefix, stage3, tools)
    passed = not any(c["differing"] or c["only_in_first"] or c["only_in_second"] for c in (fixed, second))
    executables = {name: sha(stage4 / name) for name in ("bin/gcc", f"libexec/gcc/{TRIPLE}/4.0.4/cc1",
                                                          f"libexec/gcc/{TRIPLE}/4.0.4/collect2")}
    report = {"scope": "GCC 4.0.4 fixed point (stages 2, 3 and 4 identical) from the Forth-built stage-C compiler, musl sysroot, Forth-built binutils",
              "stage_c": str(stage_c), "steps": steps, "stage3_vs_stage4": fixed,
              "stage2_vs_stage3": second, "fixed_point": passed, "stage4_sha256": executables}
    (work / "report.json").write_text(json.dumps(report, indent=2) + "\n")
    lines = [f"# Stage D: {'fixed point reached' if passed else 'NO fixed point'}", "",
             f"Stage 3 vs stage 4: {fixed['files']} files, {len(fixed['differing'])} differ"
             + (" (" + ", ".join(fixed["differing"]) + ")" if fixed["differing"] else "") + ".",
             f"Stage 2 vs stage 3: {second['files']} files, {len(second['differing'])} differ"
             + (" (" + ", ".join(second["differing"]) + ")" if second["differing"] else "") + ".", ""]
    lines += [f"- {step['stage']}: {step['seconds']} s" for step in steps]
    lines += ["", *[f"- {name}: `{digest}`" for name, digest in executables.items()]]
    (work / "report.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
