#!/usr/bin/env python3
"""Authoring/checking tool, never run by the bootstrap recipe.

Write tools/musl.recipe, a runner recipe that builds musl-1.1.24 with tcc
exactly as gcc64's `./configure && make && make install` does, with no
shell, make, sed or install program:

  mkdir      the object and install directories
  musl-gen   obj/include/bits/{alltypes,syscall}.h (for the two sed steps)
  text       obj/src/internal/version.h
  run CC     each of the 1,261 compiles, with make's exact arguments
  runargs    CC -ar rc lib/libc.a, objects in make's order
             (tools/musl-libc-objs.txt; the runner allows 127 arguments)
  copy       crt objects into lib/, then make install's 232 files into P

Input: the log of one gcc64 stage-2 musl build (make echoes every
command), BUILDROOT/logs/musl-2.log by default.  Both logs gcc64 writes
for tcc-built musl give the same commands apart from the compiler path;
the recipe's output is checked by hash (gcc64/HASHES pins tc/lib/libc.a),
so the log is authoring input, not trusted.

The recipe expects to run in an unpacked, patched musl-1.1.24 tree with
CC (the tcc to use), P (the install prefix), T (directory holding
musl-gen, runargs and musl-libc-objs.txt) and L (a log directory) set.
"""
import argparse
from pathlib import Path
import re
import shlex

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--log", default=ROOT / "build-out/gcc64/logs/musl-2.log")
parser.add_argument("--check", action="store_true")
args = parser.parse_args()

lines = Path(args.log).read_text().splitlines()
compiles, objs, crt, empty, installs = {}, None, [], [], []
cc = None
for line in lines:
    if re.match(r"(checking|configure|creating|using|components|  )", line):
        continue
    if not line or line.startswith("mkdir -p ") or line.startswith("rm -f "):
        continue
    w = shlex.split(line)
    if w[0].endswith("/tcc") and "-c" in w and "-o" in w:
        cc = cc or w[0]
        assert w[0] == cc
        out = w[w.index("-o") + 1]
        assert out.startswith("obj/") and out not in compiles
        compiles[out] = w[1:]
    elif w[0].endswith("/tcc") and w[1:3] == ["-ar", "rc"]:
        assert w[3] == "lib/libc.a" and objs is None
        objs = w[4:]
    elif w[0] == "cp" and w[1].startswith("obj/crt/"):
        crt.append((w[1], w[2]))
    elif w[0] == "touch":
        empty.append(w[1])
    elif w[0] == "./tools/install.sh":
        assert w[1:4] == ["-D", "-m", "644"]
        dst = w[5]
        prefix = dst[:dst.index("/include/")] if "/include/" in dst else dst[:dst.index("/lib/")]
        installs.append((w[4], dst[len(prefix) + 1:]))
    elif w[0] in ("sed", "cp", "printf", "true"):
        pass                                    # handled explicitly below
    else:
        raise SystemExit(f"unhandled command: {line[:100]}")
assert objs and set(objs) <= set(compiles), "archive members must be compiled"
assert len(installs) == 232 and len(crt) == 5 and len(empty) == 8

dirs = set()
def need(path):
    d = str(Path(path).parent)
    while d not in (".", ""):
        dirs.add(d)
        d = str(Path(d).parent)
for out in compiles:
    need(out)
need("obj/include/bits/x")
need("obj/src/internal/x")
need("lib/x")
pdirs = set()
for _, dst in installs:
    d = str(Path(dst).parent)
    while d not in (".", ""):
        pdirs.add(d)
        d = str(Path(d).parent)

q = lambda s: shlex.quote(s) if re.search(r"[\s'\"#\\$]", s) else s
r = ["# Generated by tools/prepare-musl-recipe.py; do not edit.",
     "# musl-1.1.24 with tcc: gcc64's configure/make/make install, as runner commands.",
     "# Needs CC, P, T and L set; runs in the unpacked, patched source tree."]
for d in sorted(dirs, key=lambda d: (d.count("/"), d)):
    r.append(f"mkdir {d}")
r.append("run 0 - ${L}/musl-gen.out ${L}/musl-gen.err ${T}/musl-gen alltypes "
         "arch/x86_64/bits/alltypes.h.in include/alltypes.h.in obj/include/bits/alltypes.h")
r.append("run 0 - ${L}/musl-gen.out ${L}/musl-gen.err ${T}/musl-gen syscall "
         "arch/x86_64/bits/syscall.h.in obj/include/bits/syscall.h")
r.append('text obj/src/internal/version.h "#define VERSION \\"1.1.24\\"\\n"')
for out in sorted(compiles):
    r.append("run 0 - ${L}/cc.out ${L}/cc.err ${CC} " + " ".join(q(a) for a in compiles[out]))
for src, dst in crt:
    r.append(f"copy {src} {dst}")
r.append("run 0 - ${L}/ar.out ${L}/ar.err ${T}/runargs ${T}/musl-libc-objs.txt ${CC} -ar rc lib/libc.a")
for e in empty:
    r.append(f'text {e} ""')
r.append("mkdir ${P}")
for d in sorted(pdirs, key=lambda d: (d.count("/"), d)):
    r.append(f"mkdir ${{P}}/{d}")
for src, dst in installs:
    r.append(f"copy {src} ${{P}}/{dst}")
recipe = "\n".join(r) + "\n"
objtxt = "\n".join(objs) + "\n"
for a in recipe.splitlines():
    assert len(a.split()) <= 127, a[:80]     # an upper bound on runner arguments

outputs = {ROOT / "tools/musl.recipe": recipe, ROOT / "tools/musl-libc-objs.txt": objtxt}
for path, text in outputs.items():
    if args.check:
        if path.read_text() != text:
            raise SystemExit(f"{path.name} is stale")
    else:
        path.write_text(text)
print(f"musl recipe: {len(compiles)} compiles, {len(objs)} archive members, "
      f"{len(installs)} installed files, {len(recipe)} bytes")
